# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tokyovania/folowup2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tokyovania/folowup2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tokyovania/folowup2/CMakeFiles /home/tokyovania/folowup2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tokyovania/folowup2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ServerRTYPE

# Build rule for target.
ServerRTYPE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ServerRTYPE
.PHONY : ServerRTYPE

# fast build rule for target.
ServerRTYPE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/build
.PHONY : ServerRTYPE/fast

#=============================================================================
# Target rules for targets named ClientRTYPE

# Build rule for target.
ClientRTYPE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ClientRTYPE
.PHONY : ClientRTYPE

# fast build rule for target.
ClientRTYPE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/build
.PHONY : ClientRTYPE/fast

src/Batch.o: src/Batch.cpp.o
.PHONY : src/Batch.o

# target to build an object file
src/Batch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Batch.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Batch.cpp.o
.PHONY : src/Batch.cpp.o

src/Batch.i: src/Batch.cpp.i
.PHONY : src/Batch.i

# target to preprocess a source file
src/Batch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Batch.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Batch.cpp.i
.PHONY : src/Batch.cpp.i

src/Batch.s: src/Batch.cpp.s
.PHONY : src/Batch.s

# target to generate assembly for a file
src/Batch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Batch.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Batch.cpp.s
.PHONY : src/Batch.cpp.s

src/Beatmap/BeatmapConfig.o: src/Beatmap/BeatmapConfig.cpp.o
.PHONY : src/Beatmap/BeatmapConfig.o

# target to build an object file
src/Beatmap/BeatmapConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Beatmap/BeatmapConfig.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Beatmap/BeatmapConfig.cpp.o
.PHONY : src/Beatmap/BeatmapConfig.cpp.o

src/Beatmap/BeatmapConfig.i: src/Beatmap/BeatmapConfig.cpp.i
.PHONY : src/Beatmap/BeatmapConfig.i

# target to preprocess a source file
src/Beatmap/BeatmapConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Beatmap/BeatmapConfig.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Beatmap/BeatmapConfig.cpp.i
.PHONY : src/Beatmap/BeatmapConfig.cpp.i

src/Beatmap/BeatmapConfig.s: src/Beatmap/BeatmapConfig.cpp.s
.PHONY : src/Beatmap/BeatmapConfig.s

# target to generate assembly for a file
src/Beatmap/BeatmapConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Beatmap/BeatmapConfig.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Beatmap/BeatmapConfig.cpp.s
.PHONY : src/Beatmap/BeatmapConfig.cpp.s

src/Behaviour.o: src/Behaviour.cpp.o
.PHONY : src/Behaviour.o

# target to build an object file
src/Behaviour.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Behaviour.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Behaviour.cpp.o
.PHONY : src/Behaviour.cpp.o

src/Behaviour.i: src/Behaviour.cpp.i
.PHONY : src/Behaviour.i

# target to preprocess a source file
src/Behaviour.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Behaviour.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Behaviour.cpp.i
.PHONY : src/Behaviour.cpp.i

src/Behaviour.s: src/Behaviour.cpp.s
.PHONY : src/Behaviour.s

# target to generate assembly for a file
src/Behaviour.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Behaviour.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Behaviour.cpp.s
.PHONY : src/Behaviour.cpp.s

src/ClientMain.o: src/ClientMain.cpp.o
.PHONY : src/ClientMain.o

# target to build an object file
src/ClientMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ClientMain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ClientMain.cpp.o
.PHONY : src/ClientMain.cpp.o

src/ClientMain.i: src/ClientMain.cpp.i
.PHONY : src/ClientMain.i

# target to preprocess a source file
src/ClientMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ClientMain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ClientMain.cpp.i
.PHONY : src/ClientMain.cpp.i

src/ClientMain.s: src/ClientMain.cpp.s
.PHONY : src/ClientMain.s

# target to generate assembly for a file
src/ClientMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ClientMain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ClientMain.cpp.s
.PHONY : src/ClientMain.cpp.s

src/Component.o: src/Component.cpp.o
.PHONY : src/Component.o

# target to build an object file
src/Component.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Component.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Component.cpp.o
.PHONY : src/Component.cpp.o

src/Component.i: src/Component.cpp.i
.PHONY : src/Component.i

# target to preprocess a source file
src/Component.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Component.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Component.cpp.i
.PHONY : src/Component.cpp.i

src/Component.s: src/Component.cpp.s
.PHONY : src/Component.s

# target to generate assembly for a file
src/Component.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Component.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Component.cpp.s
.PHONY : src/Component.cpp.s

src/Config/Config.o: src/Config/Config.cpp.o
.PHONY : src/Config/Config.o

# target to build an object file
src/Config/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Config/Config.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Config/Config.cpp.o
.PHONY : src/Config/Config.cpp.o

src/Config/Config.i: src/Config/Config.cpp.i
.PHONY : src/Config/Config.i

# target to preprocess a source file
src/Config/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Config/Config.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Config/Config.cpp.i
.PHONY : src/Config/Config.cpp.i

src/Config/Config.s: src/Config/Config.cpp.s
.PHONY : src/Config/Config.s

# target to generate assembly for a file
src/Config/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Config/Config.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Config/Config.cpp.s
.PHONY : src/Config/Config.cpp.s

src/ConfigServer.o: src/ConfigServer.cpp.o
.PHONY : src/ConfigServer.o

# target to build an object file
src/ConfigServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ConfigServer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ConfigServer.cpp.o
.PHONY : src/ConfigServer.cpp.o

src/ConfigServer.i: src/ConfigServer.cpp.i
.PHONY : src/ConfigServer.i

# target to preprocess a source file
src/ConfigServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ConfigServer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ConfigServer.cpp.i
.PHONY : src/ConfigServer.cpp.i

src/ConfigServer.s: src/ConfigServer.cpp.s
.PHONY : src/ConfigServer.s

# target to generate assembly for a file
src/ConfigServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ConfigServer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ConfigServer.cpp.s
.PHONY : src/ConfigServer.cpp.s

src/Database/Database.o: src/Database/Database.cpp.o
.PHONY : src/Database/Database.o

# target to build an object file
src/Database/Database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Database/Database.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Database/Database.cpp.o
.PHONY : src/Database/Database.cpp.o

src/Database/Database.i: src/Database/Database.cpp.i
.PHONY : src/Database/Database.i

# target to preprocess a source file
src/Database/Database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Database/Database.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Database/Database.cpp.i
.PHONY : src/Database/Database.cpp.i

src/Database/Database.s: src/Database/Database.cpp.s
.PHONY : src/Database/Database.s

# target to generate assembly for a file
src/Database/Database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Database/Database.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Database/Database.cpp.s
.PHONY : src/Database/Database.cpp.s

src/Entity.o: src/Entity.cpp.o
.PHONY : src/Entity.o

# target to build an object file
src/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Entity.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Entity.cpp.o
.PHONY : src/Entity.cpp.o

src/Entity.i: src/Entity.cpp.i
.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Entity.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s
.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Entity.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/Event.o: src/Event.cpp.o
.PHONY : src/Event.o

# target to build an object file
src/Event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Event.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Event.cpp.o
.PHONY : src/Event.cpp.o

src/Event.i: src/Event.cpp.i
.PHONY : src/Event.i

# target to preprocess a source file
src/Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Event.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Event.cpp.i
.PHONY : src/Event.cpp.i

src/Event.s: src/Event.cpp.s
.PHONY : src/Event.s

# target to generate assembly for a file
src/Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Event.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Event.cpp.s
.PHONY : src/Event.cpp.s

src/GUI/GUI.o: src/GUI/GUI.cpp.o
.PHONY : src/GUI/GUI.o

# target to build an object file
src/GUI/GUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GUI/GUI.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GUI/GUI.cpp.o
.PHONY : src/GUI/GUI.cpp.o

src/GUI/GUI.i: src/GUI/GUI.cpp.i
.PHONY : src/GUI/GUI.i

# target to preprocess a source file
src/GUI/GUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GUI/GUI.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GUI/GUI.cpp.i
.PHONY : src/GUI/GUI.cpp.i

src/GUI/GUI.s: src/GUI/GUI.cpp.s
.PHONY : src/GUI/GUI.s

# target to generate assembly for a file
src/GUI/GUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GUI/GUI.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GUI/GUI.cpp.s
.PHONY : src/GUI/GUI.cpp.s

src/GUI/GUIConfig.o: src/GUI/GUIConfig.cpp.o
.PHONY : src/GUI/GUIConfig.o

# target to build an object file
src/GUI/GUIConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GUI/GUIConfig.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GUI/GUIConfig.cpp.o
.PHONY : src/GUI/GUIConfig.cpp.o

src/GUI/GUIConfig.i: src/GUI/GUIConfig.cpp.i
.PHONY : src/GUI/GUIConfig.i

# target to preprocess a source file
src/GUI/GUIConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GUI/GUIConfig.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GUI/GUIConfig.cpp.i
.PHONY : src/GUI/GUIConfig.cpp.i

src/GUI/GUIConfig.s: src/GUI/GUIConfig.cpp.s
.PHONY : src/GUI/GUIConfig.s

# target to generate assembly for a file
src/GUI/GUIConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GUI/GUIConfig.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GUI/GUIConfig.cpp.s
.PHONY : src/GUI/GUIConfig.cpp.s

src/GraphicElement/BeatmapPanel.o: src/GraphicElement/BeatmapPanel.cpp.o
.PHONY : src/GraphicElement/BeatmapPanel.o

# target to build an object file
src/GraphicElement/BeatmapPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/BeatmapPanel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/BeatmapPanel.cpp.o
.PHONY : src/GraphicElement/BeatmapPanel.cpp.o

src/GraphicElement/BeatmapPanel.i: src/GraphicElement/BeatmapPanel.cpp.i
.PHONY : src/GraphicElement/BeatmapPanel.i

# target to preprocess a source file
src/GraphicElement/BeatmapPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/BeatmapPanel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/BeatmapPanel.cpp.i
.PHONY : src/GraphicElement/BeatmapPanel.cpp.i

src/GraphicElement/BeatmapPanel.s: src/GraphicElement/BeatmapPanel.cpp.s
.PHONY : src/GraphicElement/BeatmapPanel.s

# target to generate assembly for a file
src/GraphicElement/BeatmapPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/BeatmapPanel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/BeatmapPanel.cpp.s
.PHONY : src/GraphicElement/BeatmapPanel.cpp.s

src/GraphicElement/Button.o: src/GraphicElement/Button.cpp.o
.PHONY : src/GraphicElement/Button.o

# target to build an object file
src/GraphicElement/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/Button.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/Button.cpp.o
.PHONY : src/GraphicElement/Button.cpp.o

src/GraphicElement/Button.i: src/GraphicElement/Button.cpp.i
.PHONY : src/GraphicElement/Button.i

# target to preprocess a source file
src/GraphicElement/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/Button.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/Button.cpp.i
.PHONY : src/GraphicElement/Button.cpp.i

src/GraphicElement/Button.s: src/GraphicElement/Button.cpp.s
.PHONY : src/GraphicElement/Button.s

# target to generate assembly for a file
src/GraphicElement/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/Button.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/Button.cpp.s
.PHONY : src/GraphicElement/Button.cpp.s

src/GraphicElement/ButtonConfig.o: src/GraphicElement/ButtonConfig.cpp.o
.PHONY : src/GraphicElement/ButtonConfig.o

# target to build an object file
src/GraphicElement/ButtonConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/ButtonConfig.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/ButtonConfig.cpp.o
.PHONY : src/GraphicElement/ButtonConfig.cpp.o

src/GraphicElement/ButtonConfig.i: src/GraphicElement/ButtonConfig.cpp.i
.PHONY : src/GraphicElement/ButtonConfig.i

# target to preprocess a source file
src/GraphicElement/ButtonConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/ButtonConfig.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/ButtonConfig.cpp.i
.PHONY : src/GraphicElement/ButtonConfig.cpp.i

src/GraphicElement/ButtonConfig.s: src/GraphicElement/ButtonConfig.cpp.s
.PHONY : src/GraphicElement/ButtonConfig.s

# target to generate assembly for a file
src/GraphicElement/ButtonConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/ButtonConfig.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/ButtonConfig.cpp.s
.PHONY : src/GraphicElement/ButtonConfig.cpp.s

src/GraphicElement/LoadingScreen.o: src/GraphicElement/LoadingScreen.cpp.o
.PHONY : src/GraphicElement/LoadingScreen.o

# target to build an object file
src/GraphicElement/LoadingScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/LoadingScreen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/LoadingScreen.cpp.o
.PHONY : src/GraphicElement/LoadingScreen.cpp.o

src/GraphicElement/LoadingScreen.i: src/GraphicElement/LoadingScreen.cpp.i
.PHONY : src/GraphicElement/LoadingScreen.i

# target to preprocess a source file
src/GraphicElement/LoadingScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/LoadingScreen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/LoadingScreen.cpp.i
.PHONY : src/GraphicElement/LoadingScreen.cpp.i

src/GraphicElement/LoadingScreen.s: src/GraphicElement/LoadingScreen.cpp.s
.PHONY : src/GraphicElement/LoadingScreen.s

# target to generate assembly for a file
src/GraphicElement/LoadingScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/LoadingScreen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/LoadingScreen.cpp.s
.PHONY : src/GraphicElement/LoadingScreen.cpp.s

src/GraphicElement/RectangleButton.o: src/GraphicElement/RectangleButton.cpp.o
.PHONY : src/GraphicElement/RectangleButton.o

# target to build an object file
src/GraphicElement/RectangleButton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/RectangleButton.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/RectangleButton.cpp.o
.PHONY : src/GraphicElement/RectangleButton.cpp.o

src/GraphicElement/RectangleButton.i: src/GraphicElement/RectangleButton.cpp.i
.PHONY : src/GraphicElement/RectangleButton.i

# target to preprocess a source file
src/GraphicElement/RectangleButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/RectangleButton.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/RectangleButton.cpp.i
.PHONY : src/GraphicElement/RectangleButton.cpp.i

src/GraphicElement/RectangleButton.s: src/GraphicElement/RectangleButton.cpp.s
.PHONY : src/GraphicElement/RectangleButton.s

# target to generate assembly for a file
src/GraphicElement/RectangleButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/GraphicElement/RectangleButton.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/GraphicElement/RectangleButton.cpp.s
.PHONY : src/GraphicElement/RectangleButton.cpp.s

src/Menu/Menu.o: src/Menu/Menu.cpp.o
.PHONY : src/Menu/Menu.o

# target to build an object file
src/Menu/Menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Menu/Menu.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Menu/Menu.cpp.o
.PHONY : src/Menu/Menu.cpp.o

src/Menu/Menu.i: src/Menu/Menu.cpp.i
.PHONY : src/Menu/Menu.i

# target to preprocess a source file
src/Menu/Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Menu/Menu.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Menu/Menu.cpp.i
.PHONY : src/Menu/Menu.cpp.i

src/Menu/Menu.s: src/Menu/Menu.cpp.s
.PHONY : src/Menu/Menu.s

# target to generate assembly for a file
src/Menu/Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Menu/Menu.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Menu/Menu.cpp.s
.PHONY : src/Menu/Menu.cpp.s

src/MenuSystem.o: src/MenuSystem.cpp.o
.PHONY : src/MenuSystem.o

# target to build an object file
src/MenuSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/MenuSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/MenuSystem.cpp.o
.PHONY : src/MenuSystem.cpp.o

src/MenuSystem.i: src/MenuSystem.cpp.i
.PHONY : src/MenuSystem.i

# target to preprocess a source file
src/MenuSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/MenuSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/MenuSystem.cpp.i
.PHONY : src/MenuSystem.cpp.i

src/MenuSystem.s: src/MenuSystem.cpp.s
.PHONY : src/MenuSystem.s

# target to generate assembly for a file
src/MenuSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/MenuSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/MenuSystem.cpp.s
.PHONY : src/MenuSystem.cpp.s

src/QuadTree.o: src/QuadTree.cpp.o
.PHONY : src/QuadTree.o

# target to build an object file
src/QuadTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/QuadTree.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/QuadTree.cpp.o
.PHONY : src/QuadTree.cpp.o

src/QuadTree.i: src/QuadTree.cpp.i
.PHONY : src/QuadTree.i

# target to preprocess a source file
src/QuadTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/QuadTree.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/QuadTree.cpp.i
.PHONY : src/QuadTree.cpp.i

src/QuadTree.s: src/QuadTree.cpp.s
.PHONY : src/QuadTree.s

# target to generate assembly for a file
src/QuadTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/QuadTree.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/QuadTree.cpp.s
.PHONY : src/QuadTree.cpp.s

src/Registry.o: src/Registry.cpp.o
.PHONY : src/Registry.o

# target to build an object file
src/Registry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Registry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Registry.cpp.o
.PHONY : src/Registry.cpp.o

src/Registry.i: src/Registry.cpp.i
.PHONY : src/Registry.i

# target to preprocess a source file
src/Registry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Registry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Registry.cpp.i
.PHONY : src/Registry.cpp.i

src/Registry.s: src/Registry.cpp.s
.PHONY : src/Registry.s

# target to generate assembly for a file
src/Registry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Registry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Registry.cpp.s
.PHONY : src/Registry.cpp.s

src/SceneParsing.o: src/SceneParsing.cpp.o
.PHONY : src/SceneParsing.o

# target to build an object file
src/SceneParsing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/SceneParsing.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/SceneParsing.cpp.o
.PHONY : src/SceneParsing.cpp.o

src/SceneParsing.i: src/SceneParsing.cpp.i
.PHONY : src/SceneParsing.i

# target to preprocess a source file
src/SceneParsing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/SceneParsing.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/SceneParsing.cpp.i
.PHONY : src/SceneParsing.cpp.i

src/SceneParsing.s: src/SceneParsing.cpp.s
.PHONY : src/SceneParsing.s

# target to generate assembly for a file
src/SceneParsing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/SceneParsing.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/SceneParsing.cpp.s
.PHONY : src/SceneParsing.cpp.s

src/ServerMain.o: src/ServerMain.cpp.o
.PHONY : src/ServerMain.o

# target to build an object file
src/ServerMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ServerMain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ServerMain.cpp.o
.PHONY : src/ServerMain.cpp.o

src/ServerMain.i: src/ServerMain.cpp.i
.PHONY : src/ServerMain.i

# target to preprocess a source file
src/ServerMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ServerMain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ServerMain.cpp.i
.PHONY : src/ServerMain.cpp.i

src/ServerMain.s: src/ServerMain.cpp.s
.PHONY : src/ServerMain.s

# target to generate assembly for a file
src/ServerMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ServerMain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ServerMain.cpp.s
.PHONY : src/ServerMain.cpp.s

src/Spawner.o: src/Spawner.cpp.o
.PHONY : src/Spawner.o

# target to build an object file
src/Spawner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Spawner.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Spawner.cpp.o
.PHONY : src/Spawner.cpp.o

src/Spawner.i: src/Spawner.cpp.i
.PHONY : src/Spawner.i

# target to preprocess a source file
src/Spawner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Spawner.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Spawner.cpp.i
.PHONY : src/Spawner.cpp.i

src/Spawner.s: src/Spawner.cpp.s
.PHONY : src/Spawner.s

# target to generate assembly for a file
src/Spawner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/Spawner.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/Spawner.cpp.s
.PHONY : src/Spawner.cpp.s

src/SpritePool.o: src/SpritePool.cpp.o
.PHONY : src/SpritePool.o

# target to build an object file
src/SpritePool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/SpritePool.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/SpritePool.cpp.o
.PHONY : src/SpritePool.cpp.o

src/SpritePool.i: src/SpritePool.cpp.i
.PHONY : src/SpritePool.i

# target to preprocess a source file
src/SpritePool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/SpritePool.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/SpritePool.cpp.i
.PHONY : src/SpritePool.cpp.i

src/SpritePool.s: src/SpritePool.cpp.s
.PHONY : src/SpritePool.s

# target to generate assembly for a file
src/SpritePool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/SpritePool.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/SpritePool.cpp.s
.PHONY : src/SpritePool.cpp.s

src/TextureManager.o: src/TextureManager.cpp.o
.PHONY : src/TextureManager.o

# target to build an object file
src/TextureManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/TextureManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/TextureManager.cpp.o
.PHONY : src/TextureManager.cpp.o

src/TextureManager.i: src/TextureManager.cpp.i
.PHONY : src/TextureManager.i

# target to preprocess a source file
src/TextureManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/TextureManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/TextureManager.cpp.i
.PHONY : src/TextureManager.cpp.i

src/TextureManager.s: src/TextureManager.cpp.s
.PHONY : src/TextureManager.s

# target to generate assembly for a file
src/TextureManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/TextureManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/TextureManager.cpp.s
.PHONY : src/TextureManager.cpp.s

src/ThreadPool.o: src/ThreadPool.cpp.o
.PHONY : src/ThreadPool.o

# target to build an object file
src/ThreadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ThreadPool.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ThreadPool.cpp.o
.PHONY : src/ThreadPool.cpp.o

src/ThreadPool.i: src/ThreadPool.cpp.i
.PHONY : src/ThreadPool.i

# target to preprocess a source file
src/ThreadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ThreadPool.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ThreadPool.cpp.i
.PHONY : src/ThreadPool.cpp.i

src/ThreadPool.s: src/ThreadPool.cpp.s
.PHONY : src/ThreadPool.s

# target to generate assembly for a file
src/ThreadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/ThreadPool.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/ThreadPool.cpp.s
.PHONY : src/ThreadPool.cpp.s

src/global.o: src/global.cpp.o
.PHONY : src/global.o

# target to build an object file
src/global.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/global.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/global.cpp.o
.PHONY : src/global.cpp.o

src/global.i: src/global.cpp.i
.PHONY : src/global.i

# target to preprocess a source file
src/global.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/global.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/global.cpp.i
.PHONY : src/global.cpp.i

src/global.s: src/global.cpp.s
.PHONY : src/global.s

# target to generate assembly for a file
src/global.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/global.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/global.cpp.s
.PHONY : src/global.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/taskLoader.o: src/taskLoader.cpp.o
.PHONY : src/taskLoader.o

# target to build an object file
src/taskLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/taskLoader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/taskLoader.cpp.o
.PHONY : src/taskLoader.cpp.o

src/taskLoader.i: src/taskLoader.cpp.i
.PHONY : src/taskLoader.i

# target to preprocess a source file
src/taskLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/taskLoader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/taskLoader.cpp.i
.PHONY : src/taskLoader.cpp.i

src/taskLoader.s: src/taskLoader.cpp.s
.PHONY : src/taskLoader.s

# target to generate assembly for a file
src/taskLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServerRTYPE.dir/build.make CMakeFiles/ServerRTYPE.dir/src/taskLoader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientRTYPE.dir/build.make CMakeFiles/ClientRTYPE.dir/src/taskLoader.cpp.s
.PHONY : src/taskLoader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ClientRTYPE"
	@echo "... ServerRTYPE"
	@echo "... src/Batch.o"
	@echo "... src/Batch.i"
	@echo "... src/Batch.s"
	@echo "... src/Beatmap/BeatmapConfig.o"
	@echo "... src/Beatmap/BeatmapConfig.i"
	@echo "... src/Beatmap/BeatmapConfig.s"
	@echo "... src/Behaviour.o"
	@echo "... src/Behaviour.i"
	@echo "... src/Behaviour.s"
	@echo "... src/ClientMain.o"
	@echo "... src/ClientMain.i"
	@echo "... src/ClientMain.s"
	@echo "... src/Component.o"
	@echo "... src/Component.i"
	@echo "... src/Component.s"
	@echo "... src/Config/Config.o"
	@echo "... src/Config/Config.i"
	@echo "... src/Config/Config.s"
	@echo "... src/ConfigServer.o"
	@echo "... src/ConfigServer.i"
	@echo "... src/ConfigServer.s"
	@echo "... src/Database/Database.o"
	@echo "... src/Database/Database.i"
	@echo "... src/Database/Database.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/Event.o"
	@echo "... src/Event.i"
	@echo "... src/Event.s"
	@echo "... src/GUI/GUI.o"
	@echo "... src/GUI/GUI.i"
	@echo "... src/GUI/GUI.s"
	@echo "... src/GUI/GUIConfig.o"
	@echo "... src/GUI/GUIConfig.i"
	@echo "... src/GUI/GUIConfig.s"
	@echo "... src/GraphicElement/BeatmapPanel.o"
	@echo "... src/GraphicElement/BeatmapPanel.i"
	@echo "... src/GraphicElement/BeatmapPanel.s"
	@echo "... src/GraphicElement/Button.o"
	@echo "... src/GraphicElement/Button.i"
	@echo "... src/GraphicElement/Button.s"
	@echo "... src/GraphicElement/ButtonConfig.o"
	@echo "... src/GraphicElement/ButtonConfig.i"
	@echo "... src/GraphicElement/ButtonConfig.s"
	@echo "... src/GraphicElement/LoadingScreen.o"
	@echo "... src/GraphicElement/LoadingScreen.i"
	@echo "... src/GraphicElement/LoadingScreen.s"
	@echo "... src/GraphicElement/RectangleButton.o"
	@echo "... src/GraphicElement/RectangleButton.i"
	@echo "... src/GraphicElement/RectangleButton.s"
	@echo "... src/Menu/Menu.o"
	@echo "... src/Menu/Menu.i"
	@echo "... src/Menu/Menu.s"
	@echo "... src/MenuSystem.o"
	@echo "... src/MenuSystem.i"
	@echo "... src/MenuSystem.s"
	@echo "... src/QuadTree.o"
	@echo "... src/QuadTree.i"
	@echo "... src/QuadTree.s"
	@echo "... src/Registry.o"
	@echo "... src/Registry.i"
	@echo "... src/Registry.s"
	@echo "... src/SceneParsing.o"
	@echo "... src/SceneParsing.i"
	@echo "... src/SceneParsing.s"
	@echo "... src/ServerMain.o"
	@echo "... src/ServerMain.i"
	@echo "... src/ServerMain.s"
	@echo "... src/Spawner.o"
	@echo "... src/Spawner.i"
	@echo "... src/Spawner.s"
	@echo "... src/SpritePool.o"
	@echo "... src/SpritePool.i"
	@echo "... src/SpritePool.s"
	@echo "... src/TextureManager.o"
	@echo "... src/TextureManager.i"
	@echo "... src/TextureManager.s"
	@echo "... src/ThreadPool.o"
	@echo "... src/ThreadPool.i"
	@echo "... src/ThreadPool.s"
	@echo "... src/global.o"
	@echo "... src/global.i"
	@echo "... src/global.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/taskLoader.o"
	@echo "... src/taskLoader.i"
	@echo "... src/taskLoader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

